apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: efk-logging
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      nodeSelector:
        kubernetes.io/hostname: "{{ EFK_LOGGING.elasticsearch.nodeName }}"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: elasticsearch
          image: elasticsearch:8.16.0
          resources:
            limits:
              cpu: 2000m
            requests:
              cpu: 250m
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: cluster.name
              value: k8s-logs
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "es-cluster-0.elasticsearch.efk-logging.svc.cluster.local"
            - name: cluster.initial_master_nodes
              value: "es-cluster-0"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: elasticsearch-data-pvc
