- name: Login ArgoCD
  hosts: controlplane_init
  become: yes
  roles:
    - argocd-login

- name: Provisionar proxy-tcp no ArgoCD
  hosts: controlplane_init
  become: yes
  roles:
    - provisiona-proxy-tcp

