---
- name: Imprimir o comando join para o novo worker
  hosts: controlplane_init
  become: yes
  vars_files:
    - vars/main.yaml
  roles:
    - k8s-print-join-command
  tags:
    - print-token

- name: Fazer join do novo worker
  hosts: worker_join
  become: yes
  vars_files:
    - vars/main.yaml
  roles:
    - k8s-join-worker
  tags:
    - join-worker

