---
- name: Variáveis utilizadas para provisionar user management
  debug:
    msg:
      - "ansible_host = {{ ansible_host }}"
      - "ansible_hostname = {{ ansible_hostname }}"

- name: Provisionar manifestos RBAC
  kubernetes.core.k8s:
    namespace: argocd
    template: replica-sieweb-user-management.yaml
    state: present
    force: yes

