---
- name: Variáveis utilizadas para provisionar proxy-tcp
  debug:
    msg:
      - "ansible_host = {{ ansible_host }}"
      - "ansible_hostname = {{ ansible_hostname }}"
      - "REPO_PROXY_TCP.repo = {{ REPO_PROXY_TCP.repo }}"
      - "REPO_PROXY_TCP.path = {{ REPO_PROXY_TCP.path }}"
      - "REPO_PROXY_TCP.dest_server = {{ REPO_PROXY_TCP.dest_server }}"
      - "REPO_PROXY_TCP.sync_policy = {{ REPO_PROXY_TCP.sync_policy }}"
      - "REPO_PROXY_TCP.revision = {{ REPO_PROXY_TCP.revision }}"

- name: Verificando se app/proxy-tcp já está provisionado no ArgoCD
  shell: kubectl -n argocd get app/proxy-tcp --ignore-not-found
  register: existe_app

- name: Registrando proxy-tcp no ArgoCD
  shell: argocd app create proxy-tcp --repo {{ REPO_PROXY_TCP.repo }} --path {{ REPO_PROXY_TCP.path }} --dest-server {{ REPO_PROXY_TCP.dest_server }} --dest-namespace proxy-reverso --sync-policy {{ REPO_PROXY_TCP.sync_policy }} --revision {{ REPO_PROXY_TCP.revision }}
  when: existe_app.stdout == ""

