---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ ansible_host }}
  share: {{ VOLUME_NFS }}
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
- nfsvers=4.2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:  
    storageclass.kubernetes.io/is-default-class: "true"
  name: local-storage
reclaimPolicy: Retain
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
