apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: efk-logging
data:
  kibana.yml: |
    server.host: 0.0.0.0
    server.shutdownTimeout: 5s
    server.publicBaseUrl: https://{{ EFK_LOGGING.kibana.ingress.host }}
    elasticsearch.hosts: ['https://es-cluster-0.elasticsearch.efk-logging.svc.cluster.local:9200']
    monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.serviceAccountToken: {{ EFK_LOGGING.elasticsearch.service_account_token }}
    elasticsearch.ssl.certificateAuthorities: [/usr/share/kibana/data/ca_1732054314128.crt]
    xpack.fleet.outputs: [{id: fleet-default-output, name: default, is_default: true, is_default_monitoring: true, type: elasticsearch, hosts: ['https://es-cluster-0.elasticsearch.efk-logging.svc.cluster.local:9200'], ca_trusted_fingerprint: {{ EFK_LOGGING.elasticsearch.ca_trusted_fingerprint }}}]
