---
- name: Aguardar kube-system ficar pronto
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf wait -n kube-system --timeout=300s --for=condition=Available deploy/coredns
  args:
    executable: /bin/bash
  ignore_errors: true

