apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: efk-logging
resources:
  - fluentd-sa.yaml
  - fluentd-rbac.yaml
  - fluentd-daemonset.yaml

configMapGenerator:
  - name: fluentd-config
    files:
      - fluent.conf
      - conf.d/kubernetes.conf
      - conf.d/efk-k8s-loadbalancer.conf
      - conf.d/efk-ufsm-proxy-tcp.conf
      - conf.d/efk-ufsm-proxy-reverso.conf
      - conf.d/efk-ufsm-sieweb.conf
      - conf.d/efk-ufsm-sieweb-timer.conf
