[controlplane]
vm-controlplane-01    ansible_host=192.168.20.11
vm-controlplane-02    ansible_host=192.168.20.12
vm-controlplane-03    ansible_host=192.168.20.13

[controlplane_init]
vm-controlplane-01    ansible_host=192.168.20.11

[controlplane_join]
vm-controlplane-02    ansible_host=192.168.20.12
vm-controlplane-03    ansible_host=192.168.20.13

# IMPORTANTE!!!
# Ao instalar um cluster novo, descomente TODOS os workers desejados
# Ao adicionar um novo worker em um cluster existente, deixar apenas o worker que vai ser adicionado
[worker_join]
vm-worker-01          ansible_host=192.168.20.16
vm-worker-02          ansible_host=192.168.20.17
vm-worker-03          ansible_host=192.168.20.18
; vm-worker-04          ansible_host=192.168.20.19

[worker]
vm-worker-01          ansible_host=192.168.20.16
vm-worker-02          ansible_host=192.168.20.17
vm-worker-03          ansible_host=192.168.20.18
;vm-worker-04          ansible_host=192.168.20.19

[proxy]
vm-worker-01          ansible_host=192.168.20.16

[nfs]
vm-controlplane-01    ansible_host=192.168.20.11

[all:vars]
ansible_ssh_private_key_file=~/.ssh/k8s-multinode
ansible_user=vagrant

